import {
  Github,
  Twitter,
  Linkedin,
  Mail,
  Globe,
  Cpu,
  Layers,
  Terminal,
  Code2,
  Sparkles,
  Database,
  Layout,
  Box,
  Instagram,
  Book,
  Projector,
  Facebook,
  Video,
} from "lucide-react";

export const SECTIONS = [
  {
    title: "SOCIALS",
    items: [
      {
        name: "LINKEDIN",
        icon: <Linkedin className="w-5 h-5" />,
        url: "https://www.linkedin.com/in/cedrick-joseph-mariano-499115277/",
        meta: "Cedrick Joseph Mariano",
        color: "#0ea5e9",
      },
      {
        name: "GITHUB",
        icon: <Github className="w-5 h-5" />,
        url: "https://github.com/icodecedd",
        meta: "github.com/icodecedd",
        color: "#ffffff",
      },
      {
        name: "INSTAGRAM",
        icon: <Instagram className="w-5 h-5" />,
        url: "https://www.instagram.com/chaoscedd_/",
        meta: "@chaoscedd_",
        color: "#f97316",
      },
      {
        name: "THREADS",
        icon: <Twitter className="w-5 h-5" />,
        url: "https://www.threads.com/@chaoscedd_?hl=en",
        meta: "@chaoscedd_",
        color: "#94a3b8",
      },
      {
        name: "FACEBOOK",
        icon: <Facebook className="w-5 h-5" />,
        url: "https://web.facebook.com/cedrickjosephmariano",
        meta: "Cedrick Joseph Mariano",
        color: "#0ea5e9",
      },
      {
        name: "TIKTOK",
        icon: <Video className="w-5 h-5" />,
        url: "https://www.tiktok.com/@chaochaos__",
        meta: "@chaochaos__",
        color: "#ff0050",
      },
      {
        name: "EMAIL",
        icon: <Mail className="w-5 h-5" />,
        url: "mailto:marianocedrick3@gmail.com",
        meta: "Direct line",
        color: "#94a3b8",
      },
    ],
  },
  {
    title: "PROJECTS",
    items: [
      {
        name: "DISK SCHEDULING",
        status: "FINISHED",
        url: "https://github.com/icodecedd/disk-scheduling",
        icon: <Database className="w-5 h-5" />,
        meta: "OS Algorithms",
        color: "#10b981",
      },
      {
        name: "PAGE REPLACEMENT",
        status: "FINISHED",
        url: "https://github.com/icodecedd/page-replacement",
        icon: <Layers className="w-5 h-5" />,
        meta: "Memory Management",
        color: "#10b981",
      },
      {
        name: "SISJUAN",
        status: "FINISHED",
        url: "https://github.com/icodecedd/SISJUAN",
        icon: <Book className="w-5 h-5" />,
        meta: "Academic System",
        color: "#10b981",
      },
      {
        name: "REQUESTOR",
        status: "ONGOING",
        url: "https://github.com/icodecedd/ReQuestor",
        icon: <Projector className="w-5 h-5" />,
        meta: "Management Tool",
        color: "#f97316",
      },
      {
        name: "ORBYTE STUDIO",
        status: "FINISHED",
        url: "https://orbyte-studio.vercel.app/home",
        icon: <Globe className="w-5 h-5" />,
        meta: "Multimedia Management",
        color: "#10b981",
      },
      {
        name: "DEBUGGING DOJO",
        status: "FINISHED",
        url: "https://debugging-dojo.vercel.app/",
        icon: <Terminal className="w-5 h-5" />,
        meta: "Code Training",
        color: "#10b981",
      },
    ],
  },
];
